In [2]:
import numpy as np

para hacer reshape simplemente tengo que multiplicar filas y vcolumnas y encontrar el numero que divide exactamente creo que esto se llama divisor 

In [2]:

print("version numpy",np.__version__)
array = np.array([1,2,3])
print(array,"\n")
print(array.shape,"1 dimension")
array2d = np.array([[12,15,16],[11,14,13]])
print(array2d,"\n")
print(array2d.shape,"2 dimensiones")
array3d = np.array([[[3,5,7],[2,3,4],[8,9,1]]])
print(array3d,"\n")
print(array3d.shape,"3 dimensiones")
array_vacio = np.zeros((30,70))
print(array_vacio,"vacio")
print(array_vacio.shape,"vacio ma g")
array_rangos = np.arange(11)
print(array_rangos)
array_rango_prueba = np.arange(0,21,4)
print(array_rango_prueba)
array_random = np.random.random((2,2))
print(array_random,"randon")
array_aleatorio_int = np.random.randint((2,2))
print("enteritos",array_aleatorio_int)
linspace = np.linspace(0,1,5)
print("lindo",linspace)
linspace2 = np.linspace(0,10,5)
print("lindo2",linspace2)




version numpy 2.2.1
[1 2 3] 

(3,) 1 dimension
[[12 15 16]
 [11 14 13]] 

(2, 3) 2 dimensiones
[[[3 5 7]
  [2 3 4]
  [8 9 1]]] 

(1, 3, 3) 3 dimensiones
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] vacio
(30, 70) vacio ma g
[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  4  8 12 16 20]
[[0.72506204 0.74973821]
 [0.78027369 0.12167868]] randon
enteritos [0 1]
lindo [0.   0.25 0.5  0.75 1.  ]
lindo2 [ 0.   2.5  5.   7.5 10. ]


In [17]:
arr1d = np.array([0,7,10])
print(arr1d[0])
print(arr1d[-1])
arr2d = np.array([
    [10,15,20],
    [25,30,35],
    [40,45,50]

])
print(arr2d[1][2])
arr_2d1 = np.array([
    [10,15,20],
    [40,45,50],
    [101,106,111],
    [251,301,351],
    [401,451,501]

])
print(arr_2d1[:,2])
print("array decimal",np.arange(0,3,0.2))
print("array_inverso",np.arange(50,25,-1))
arr = np.arange(10,0,-1)
print("slice",arr[2:10])
print("slice_salto",arr[4:9:2])
print("slice_salto",arr[1:9:3])
print("slice_salto",arr[0:6:][::-5])
print(arr)
#2,3,4,5
indice_cinco = np.where(arr==5)
print("dime to",indice_cinco)
indice_dos = np.where(arr==2)
print("dime to kako",indice_dos)

print("slice_salto",arr[8:4:-1])




0
10
35
[ 20  50 111 351 501]
array decimal [0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8]
array_inverso [50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26]
slice [8 7 6 5 4 3 2 1]
slice_salto [6 4 2]
slice_salto [9 6 3]
slice_salto [ 5 10]
[10  9  8  7  6  5  4  3  2  1]
dime to (array([5]),)
dime to kako (array([8]),)
slice_salto [2 3 4 5]


In [15]:
array2de = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("slice 2 dimensiones", array2de[:, 1:])
array_3d = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],  # Primer bloque (dimensión 0)  es como la estructura de una estanteria o como un calendario mes
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],  # Segundo bloque (dimensión 1) la balda de la estanteria  semana 
    [[19, 20, 21], [22, 23, 24], [25, 26, 27]]  # Tercer bloque (dimensión 2) el objeto en concreto de la estanteria dia 
])
print("a ver",array_3d[1,2,:] )
print("dimensiones",array_3d[2,1,1] )
#con dos puntos solo es como si hiciera un bucle y recorro todo el indice 

print("dimesiones3d",array_3d[:,1,0])
# en este caso hay k darle un rango mas el normal seria de 0,2 pero claro en el 2 se para no esta incluido asique recurro al 3 

print("dimesiones3d",array_3d[0:3,1,0])




slice 2 dimensiones [[2 3]
 [5 6]
 [8 9]]
a ver [16 17 18]
dimensiones 23
dimesiones3d [ 4 13 22]
dimesiones3d [ 4 13 22]
