In [1]:
import numpy as np

In [27]:
nombre_productos = np.array(["Smartphone","Tablet","Laptop","Auriculares","Teclado"])
print(nombre_productos)
cantidad_stock = np.array([["Smartphone",50],["Tablet",30],["Laptop",15],["Auriculares",40],["Teclado",60]])
print(cantidad_stock)
registro_ventas = np.array([[5, 3, 2, 6, 4],[7, 4, 1, 8, 5],[6, 2, 3, 5, 4]])
print(registro_ventas)
productos_no_vendidos = np.zeros((5,5))
print(productos_no_vendidos)
productos_en_promocion = np.ones((2,2))
productos_no_en_promocion = np.zeros((3,3))
print(productos_no_en_promocion)
print(productos_en_promocion)
precio_de_productos = np.arange(50,1000,50)
print(precio_de_productos)
cantidad_vendida = np.random.randint(low=1, high=10, size=5)
print(cantidad_vendida)
descuentos = np.empty((5,1))
print(descuentos)
cambio_ventas = np.linspace(0,1000,5)
print(cambio_ventas)















['Smartphone' 'Tablet' 'Laptop' 'Auriculares' 'Teclado']
[['Smartphone' '50']
 ['Tablet' '30']
 ['Laptop' '15']
 ['Auriculares' '40']
 ['Teclado' '60']]
[[5 3 2 6 4]
 [7 4 1 8 5]
 [6 2 3 5 4]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[ 50 100 150 200 250 300 350 400 450 500 550 600 650 700 750 800 850 900
 950]
[1 5 6 2 5]
[[2.31297541e-312]
 [2.41907520e-312]
 [2.37663529e-312]
 [2.35541533e-312]
 [2.14321575e-312]]
[   0.  250.  500.  750. 1000.]


In [17]:
#indexacion y seleccion de arrays con numpy ejercicio 3
array1d = np.arange(1,11)
print(array1d)
#array_tester = np.arange(1,9).reshape((3,3))
#print(array_tester)
#array_2d = array_base.reshape((3,3)) 
array2d = np.arange(9).reshape((3,3))
print(array2d)
print(array2d.ndim)
extraccion1d = int(array1d[0]),int(array1d[9])
print(array1d[0])
print(extraccion1d)
extraccion2d = array2d[0][0]
print(extraccion2d) 
extraccion2d_final = array2d[2][2]
print(extraccion2d_final)
ubicando_array2d = array2d[1][2]
print(ubicando_array2d)
print(array2d[0])
print(array2d[0][1])
print(array2d[1][1])
print(array2d[2][1])
#forma correcta preguntar 
print(array2d[:,1])


[ 1  2  3  4  5  6  7  8  9 10]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
2
1
(1, 10)
0
8
5
[0 1 2]
1
4
7
[1 4 7]


In [19]:
# pruebas
array2d = np.arange(9).reshape((3,3))
print(array2d)
print(array2d[0])
print(array2d[0][1])
print(array2d[1][1])
print(array2d[2][1])
print(array2d[0:2][1])
#forma correcta preguntar 
print(array2d[:,1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]
1
4
7
klk [3 4 5]
[1 4 7]


In [4]:
arraytester = np.random.randint(low=1, high=255,size=48)
print(arraytester)
rgb = arraytester.reshape(4,4,3)
print(rgb)
print("primer pixel",rgb[0,0, :])
print("ultimo pixel",rgb[-1,-1, :])
print("segunda fila tercera columna",rgb[0,1,2])
print("primera fila",rgb[0,:,:])
print ("canal azul",rgb[2,2 ,:])
print("recorte central",rgb[1:3, 1:3, :])

[115 130 117  69 170  17  88  10   1 199  63   3 175 186 186  20 145 184
 141 190   7  97 141  63 192 109 154  15 108  62 111 155 126 190 164 197
   8 191 198 183 219 243 102 123   2 201  62 175]
[[[115 130 117]
  [ 69 170  17]
  [ 88  10   1]
  [199  63   3]]

 [[175 186 186]
  [ 20 145 184]
  [141 190   7]
  [ 97 141  63]]

 [[192 109 154]
  [ 15 108  62]
  [111 155 126]
  [190 164 197]]

 [[  8 191 198]
  [183 219 243]
  [102 123   2]
  [201  62 175]]]


In [ ]:
Punto_1 = [2,3,5,7,11],[2,3,5,7,11]
Punto_2 = [1,4,6,8,10],[1,4,6,8,10]
array_1 = np.array(Punto_1)
array_2 = np.array(Punto_2)
print(np.linalg.norm(array_1-array_2))

In [8]:
calificaciones = np.array([
    [88, 78, 64, 92, 57, 70, 88, 68, 72, 60],
    [60, 73, 85, 89, 73, 52, 71, 51, 73, 93],
    [79, 87, 51, 70, 82, 61, 71, 93, 74, 98],
    [76, 91, 77, 65, 64, 96, 93, 52, 86, 56],
    [70, 58, 88, 67, 53, 74, 63, 99, 58, 75],
    [82, 79, 91, 88, 66, 78, 79, 63, 59, 89],
    [56, 66, 73, 77, 75, 80, 70, 64, 88, 60],
    [80, 62, 79, 85, 92, 72, 80, 69, 78, 66],
    [88, 90, 69, 77, 66, 72, 65, 73, 92, 81],
    [60, 80, 69, 94, 81, 88, 93, 60, 58, 79],
    [78, 72, 74, 81, 67, 93, 60, 72, 85, 92],
    [86, 90, 70, 64, 93, 58, 61, 95, 79, 84],
    [85, 77, 91, 85, 61, 63, 58, 68, 65, 90],
    [71, 79, 69, 58, 75, 78, 62, 82, 77, 59],
    [87, 76, 72, 68, 88, 65, 75, 90, 69, 79],
    [78, 71, 94, 67, 72, 88, 58, 79, 91, 67],
    [67, 64, 85, 81, 70, 84, 79, 73, 62, 77],
    [90, 61, 60, 91, 72, 89, 77, 75, 76, 83],
    [94, 83, 80, 59, 65, 75, 63, 92, 68, 60],
    [80, 81, 68, 95, 72, 93, 89, 59, 81, 85],
    [88, 63, 90, 77, 69, 72, 85, 78, 61, 93],
    [91, 65, 79, 92, 63, 74, 87, 70, 92, 85],
    [92, 80, 76, 72, 81, 87, 64, 74, 70, 67],
    [72, 83, 91, 58, 67, 88, 81, 76, 74, 92],
    [84, 91, 81, 77, 80, 63, 70, 79, 89, 65],
    [66, 65, 77, 58, 79, 61, 86, 72, 64, 74],
    [94, 74, 83, 89, 77, 68, 81, 92, 70, 68],
    [73, 72, 82, 80, 79, 64, 69, 60, 76, 79],
    [82, 79, 75, 89, 85, 81, 62, 64, 60, 92],
    [87, 88, 80, 74, 85, 90, 75, 68, 68, 71],
    [81, 79, 85, 76, 64, 85, 71, 77, 67, 93],
    [82, 89, 77, 72, 66, 84, 92, 60, 67, 65],
    [90, 63, 94, 67, 88, 93, 79, 64, 88, 80],
    [81, 90, 72, 76, 74, 93, 88, 84, 80, 65],
    [86, 75, 67, 81, 93, 79, 91, 64, 78, 74],
    [69, 85, 90, 91, 60, 76, 84, 78, 74, 64],
    [67, 91, 94, 78, 81, 73, 62, 67, 60, 92],
    [85, 79, 73, 60, 85, 90, 82, 75, 74, 68],
    [91, 83, 77, 92, 74, 68, 64, 92, 90, 92],
    [65, 93, 88, 82, 92, 67, 79, 68, 81, 93],
    [92, 79, 90, 92, 72, 80, 61, 75, 86, 90],
    [80, 67, 76, 84, 92, 90, 79, 93, 74, 88],
    [60, 79, 90, 93, 64, 61, 85, 76, 92, 72],
    [88, 67, 72, 64, 80, 90, 79, 75, 85, 81],
    [79, 92, 75, 72, 92, 81, 79, 70, 68, 68],
    [65, 60, 79, 89, 79, 82, 86, 64, 60, 81],
    [92, 81, 60, 79, 94, 78, 80, 91, 85, 68],
    [79, 64, 81, 72, 68, 75, 80, 94, 79, 61],
    [79, 94, 64, 89, 80, 85, 74, 82, 65, 91]
])
## axis 1 igual a columnas axix 0 igual a columas actua sobre las columas axix 1 actua sobre filas

normalizacionl2 = [ np.linalg.norm(calificacion) for calificacion in calificaciones]
print("la normalizacion l2 ", normalizacionl2)
for x in range(len(normalizacionl2)):
    print("la normalizacion por asignatura es :",normalizacionl2[x])
for x in range(10):
    print("calificaciones por asignatura",np.linalg.norm(calificaciones[:,x]))
for x in range(len(calificaciones[0])):
    print("calificaciones por asignatura con  otro metodo",np.linalg.norm(calificaciones[:,x]))
    print("asignatura",x)
print("las calificaciones utilizando axis",np.linalg.norm(calificaciones, axis=0, keepdims=True ))
print("la sumas de todas las calificaciones por  asignatura",np.sum(calificaciones,axis=0))
print("la suma de todas las notas",np.sum(calificaciones,axis=1))


    




la normalizacion l2  [np.float64(235.98516902551313), np.float64(231.7930111112067), np.float64(246.02032436365903), np.float64(243.73756378531397), np.float64(227.02643017939565), np.float64(247.06679258856298), np.float64(226.0862667213557), np.float64(242.81474419812318), np.float64(246.2782978664584), np.float64(244.45040396775784), np.float64(246.81166909204273), np.float64(250.0959815750745), np.float64(238.03991261971174), np.float64(226.03981950090122), np.float64(244.64055264816582), np.float64(244.44426767670376), np.float64(235.94490882407274), np.float64(247.0344105585293), np.float64(236.8818270783979), np.float64(256.18547968220213), np.float64(247.7216179504728), np.float64(254.58593833909995), np.float64(242.72412323458911), np.float64(249.4554068365727), np.float64(247.9576576756604), np.float64(223.5799633240868), np.float64(253.42454498331452), np.float64(233.13515393436487), np.float64(245.56261930513773), np.float64(249.85595850409493), np.float64(247.4510052515447

In [14]:
v1 = [3, 4, 0]
v2 = [4, 3, 1]
print(np.cross(v1,v2))
extra_v1 = [3, 2, 0]
extra_v2 = [4, 1, 12]
print(np.cross(extra_v1,extra_v2))
extra_v1_2d = [3, 2]
extra_v2_2d = [4, 1]
print(np.cross(extra_v1_2d,extra_v2_2d))

[ 4 -3 -7]
[ 24 -36  -5]
-5


C:\Users\Manu\AppData\Local\Temp\ipykernel_19276\374326904.py:9: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  print(np.cross(extra_v1_2d,extra_v2_2d))


In [19]:
tiempo_atleta = np.array([11, 22, 50, 110, 250])
print(tiempo_atleta)
importancia_pruebas = np.array([0.4, 0.3, 0.2, 0.1, 0.05])
print(np.dot(tiempo_atleta,importancia_pruebas))

[ 11  22  50 110 250]
44.5


In [3]:
jugadores = np.array([
    [10,7,300,25,40],
    [15,10,250,30,50],
    [5,12,280,20,35],
    [8,6,310,15,38],
    [12,9,270,28,45]
])
print(jugadores)
jugadores_normalizados = jugadores / np.linalg.norm(jugadores,axis=0)
print(jugadores_normalizados)

[[ 10   7 300  25  40]
 [ 15  10 250  30  50]
 [  5  12 280  20  35]
 [  8   6 310  15  38]
 [ 12   9 270  28  45]]
[[0.42333376 0.34570536 0.47440095 0.46154065 0.42654687]
 [0.63500064 0.4938648  0.39533413 0.55384878 0.53318359]
 [0.21166688 0.59263776 0.44277422 0.36923252 0.37322851]
 [0.33866701 0.29631888 0.49021432 0.27692439 0.40521953]
 [0.50800051 0.44447832 0.42696086 0.51692552 0.47986523]]


In [26]:
carreras = np.array([
    [1.27,2.13,1.9,3.2,2.7,1.25,1.22,1.4,1.7,1.19],
    [4.27,1.13,4.9,2.2,24.7,7.25,4.22,3.4,2.7,9.19],
    [2.26,3.13,5.9,1.2,7.7,4.25,1.38,2.4,5.7,8.19],
    [1.25,4.13,7.9,2.2,1.7,3.25,1.20,4.4,4.7,7.19],
    [1.24,8.13,2.9,4.2,3.7,2.25,1.21,6.4,3.7,6.19]
])
print(carreras.shape)

#print(carreras.reshape(2,25))
print(carreras.ravel())
print("media de los pilotos en cada carrera",np.median(carreras))
penalizacion =  carreras +2
#print(penalizacion)
print("carreras con penalizacion media de columnas",np.median(penalizacion,axis=1))
print("carreras con penalizacion media de filas",np.median(penalizacion,axis=0))

primer_piloto = carreras[0,:]
segundo_piloto = carreras[1,:]
producto_escalar = np.dot(primer_piloto,segundo_piloto)
print(producto_escalar)
tres_primeras_carreras_primerpiloto = primer_piloto[0:3]
tres_primeras_carreras_segundo_piloto = segundo_piloto[0:3]
producto_cruzado = np.cross(tres_primeras_carreras_primerpiloto,tres_primeras_carreras_segundo_piloto)
print(producto_cruzado)
carreras_normalizadas = carreras / np.linalg.norm(carreras,keepdims=True)
print(carreras_normalizadas)




(5, 10)
[ 1.27  2.13  1.9   3.2   2.7   1.25  1.22  1.4   1.7   1.19  4.27  1.13
  4.9   2.2  24.7   7.25  4.22  3.4   2.7   9.19  2.26  3.13  5.9   1.2
  7.7   4.25  1.38  2.4   5.7   8.19  1.25  4.13  7.9   2.2   1.7   3.25
  1.2   4.4   4.7   7.19  1.24  8.13  2.9   4.2   3.7   2.25  1.21  6.4
  3.7   6.19]
media de los pilotos en cada carrera 3.165
carreras con penalizacion media de columnas [3.55  6.245 5.69  5.69  5.7  ]
carreras con penalizacion media de filas [3.27 5.13 6.9  4.2  5.7  5.25 3.22 5.4  5.7  9.19]
125.3668
[ 8.29  1.89 -7.66]
[[0.03273406 0.05490044 0.04897222 0.08247953 0.06959211 0.03221857
  0.03144532 0.0360848  0.04381725 0.03067208]
 [0.11005863 0.02912559 0.12629679 0.05670468 0.6366389  0.18686769
  0.10876988 0.0876345  0.06959211 0.23687091]
 [0.05825117 0.08067529 0.15207164 0.03092982 0.19846638 0.10954313
  0.0355693  0.06185965 0.14691667 0.21109606]
 [0.03221857 0.10645015 0.20362135 0.05670468 0.04381725 0.08376828
  0.03092982 0.11340936 0.12114181

In [20]:
"""
NumPy (Numerical Python) es una librería de Python utilizada principalmente para 
el manejo y procesamiento de arrays multidimensionales (también conocidos como 
matrices o tensores) y para realizar cálculos numéricos de forma eficiente. Es una 
de las herramientas más importantes en la programación científica debido a sus potentes 
características, como el manejo de grandes volúmenes de datos numéricos y su integración 
con otras librerías populares.

Características clave de NumPy:
- Arrays multidimensionales: NumPy proporciona una estructura de datos llamada `ndarray` 
  que permite almacenar y manipular datos en arrays de cualquier dimensión. Esto facilita 
  realizar operaciones matemáticas de manera rápida y eficiente sobre grandes conjuntos 
  de datos.
  
- Operaciones vectorizadas: NumPy soporta operaciones vectorizadas, lo que significa 
  que es posible realizar cálculos sobre todos los elementos de un array sin necesidad 
  de escribir bucles explícitos. Esto hace que el código sea más limpio y eficiente.

- Funciones matemáticas y estadísticas: La librería incluye funciones avanzadas para 
  álgebra lineal (producto matricial, determinantes, valores propios), transformadas rápidas 
  de Fourier (FFT), estadísticas (media, desviación estándar, etc.), y otros cálculos numéricos.

- Compatibilidad con otras librerías: NumPy es la base de muchas otras librerías populares 
  en Python, como SciPy, pandas, Matplotlib y scikit-learn, lo que facilita la creación 
  de aplicaciones complejas para el análisis de datos, aprendizaje automático, simulaciones 
  científicas, entre otros.

Usos comunes de NumPy en programación científica:
- Cálculos numéricos: Realiza operaciones matemáticas de alto rendimiento en matrices y 
  vectores, como sumas, multiplicaciones, transposiciones, etc.

- Análisis de datos: Es ampliamente utilizado en ciencia de datos y estadística para 
  manipular y analizar grandes volúmenes de datos numéricos.

- Simulación científica: Permite simular sistemas físicos o realizar experimentos computacionales 
  a través de matrices y otros objetos matemáticos.

- Álgebra lineal: Resuelve sistemas de ecuaciones lineales, realiza descomposiciones matriciales, 
  entre otros cálculos.

- Machine learning: Muchas técnicas de aprendizaje automático utilizan NumPy para manejar y 
  procesar grandes cantidades de datos, como matrices de características o tensores de entrada.


"""
"""
La historia de NumPy comienza en los años 90, cuando Python estaba ganando 
popularidad como un lenguaje accesible para la programación en general, pero 
no contaba con herramientas adecuadas para cálculos numéricos eficientes. 

1. **SciPy y el auge de Python en ciencia computacional** (1990s):
   Durante esa década, Python se consolidaba como un lenguaje versátil, pero para 
   trabajos científicos y cálculos numéricos, la comunidad necesitaba soluciones 
   más eficientes. No existían librerías optimizadas para el manejo de matrices 
   y álgebra lineal, fundamentales en disciplinas como la ciencia computacional, 
   la ingeniería y el análisis de datos.

2. **Creación de Numeric** (1995):
   En 1995, **Jim Hugunin** y otros colaboradores desarrollaron **Numeric**, una 
   librería que permitía realizar operaciones numéricas sobre arrays en Python, 
   utilizando C para mejorar el rendimiento. Numeric fue una de las primeras soluciones 
   para manejar arrays multidimensionales y realizar cálculos matemáticos de manera 
   eficiente.

3. **Creación de Numarray** (2000):
   Al mismo tiempo que Numeric estaba ganando popularidad, se creó **Numarray**, 
   una librería similar pero con algunas mejoras, especialmente en el manejo de 
   grandes arrays. **Todd Millstein** y otros miembros de la comunidad trabajaron en su desarrollo.

4. **Fusión de Numeric y Numarray** (2005):
   Con el tiempo, los desarrolladores se dieron cuenta de la duplicación de esfuerzos 
   entre Numeric y Numarray, y decidieron crear una solución unificada. Esto dio lugar a 
   **NumPy**, una nueva librería que combinaba lo mejor de ambas, mejorando la eficiencia 
   y ofreciendo más funcionalidades.

   **Travis Oliphant**, un matemático y desarrollador clave en la comunidad Python, fue 
   el principal impulsor de esta unificación. Ya estaba trabajando en **SciPy**, una librería 
   fundamental para la computación científica, y vio que la fusión de Numeric y Numarray sería 
   la solución más eficiente para la comunidad.

5. **Lanzamiento de NumPy** (2006):
   NumPy fue lanzado oficialmente en 2006 y rápidamente se consolidó como una de las 
   librerías más importantes para la programación científica en Python. Con su capacidad 
   para manejar arrays multidimensionales, realizar operaciones vectorizadas y servir como 
   base para otras librerías científicas como SciPy, pandas y Matplotlib, NumPy se convirtió 
   en una herramienta esencial.

En resumen, NumPy nació de la necesidad de contar con herramientas numéricas eficientes 
en Python, y con el tiempo se ha convertido en la columna vertebral de la computación científica 
en este lenguaje.
"""
"""
Diferencias entre una lista de Python y un array de NumPy:

1. **Naturaleza y estructura**:
   - Las listas de Python son estructuras genéricas que permiten almacenar elementos de diferentes tipos de datos 
     (por ejemplo, números, cadenas o incluso otras listas). 
   - Los arrays de NumPy, en cambio, están diseñados para trabajar con datos homogéneos, es decir, todos los elementos 
     deben ser del mismo tipo, como enteros o flotantes.

2. **Eficiencia y rendimiento**:
   - Las listas son menos eficientes en términos de velocidad y uso de memoria debido a su naturaleza flexible y genérica.
   - Los arrays de NumPy son más rápidos y ocupan menos memoria al realizar operaciones matemáticas, ya que están optimizados 
     para cálculos científicos y numéricos utilizando bloques de memoria contiguos.

3. **Operaciones matemáticas**:
   - Las listas no soportan operaciones matemáticas elementales directamente. Por ejemplo, sumar 2 a cada elemento 
     de una lista requiere un proceso manual o el uso de estructuras adicionales.
   - Los arrays de NumPy están diseñados para realizar operaciones matemáticas de manera directa y eficiente, como 
     sumas, restas, multiplicaciones o funciones estadísticas avanzadas.

4. **Dimensiones y complejidad**:
   - Aunque las listas pueden simular estructuras de múltiples dimensiones (listas anidadas), manejar y operar con ellas 
     se vuelve complicado y poco eficiente.
   - Los arrays de NumPy soportan naturalmente múltiples dimensiones (1D, 2D, 3D, etc.) y proporcionan herramientas 
     específicas para su manipulación, como transposiciones o redimensionamientos.

5. **Aplicaciones y propósito**:
   - Las listas son ideales para datos heterogéneos o estructuras simples donde no se requieren cálculos matemáticos complejos.
   - Los arrays de NumPy están diseñados para trabajar en ámbitos científicos, matemáticos y de procesamiento de datos, 
     donde la velocidad y las operaciones vectorizadas son esenciales.
""" 



array1d = np.arange(20)
print(array1d)
array_0 = np.zeros(10)
print(array_0)
array_1 = np.ones(10)
print(array_1)


array2d = np.arange(20).reshape(2,10)
print(array2d)
array3d = np.arange(40).reshape(4,5,2)
print(array3d)
#a los valores se accede a traves de indices [] y puedes hacer uso de  la notacion slice [1:3:1] primer numero inicio 2 numero fin y tercer numero paso o salto 
array_slide = np.arange(10)
print(array_slide)
array_slide[0] =15
print(array_slide)
print(array_slide[0:8:1])
#los ejes axis son los ejes que indican la fila y la columna de un array bidimensional axix 1 actua sobre columnas y axix 0 actua sobre filas
array2d_axix = np.arange(20).reshape(2,10)
print(array2d_axix)
print("actuo sobre columnas",np.sum(array2d,axis=1))
print("actuo sobre columnas",np.sum(array2d,axis=0))
#la diferencia entre producto  escalar y el producto cruzado es el producto escalar sirve para dar un valor a 2 array y poder hacer comparaciones el producto cruzado solo actua sobre arrays con 3 valores  puesto que se usa para representar los ejes x y z y se usa para calcular la desviacion y los angulos 
array_ejemplo1 = np.array([1,2,3])
array_ejemplo2 = np.array([7,4,1])
print(np.dot(array_ejemplo1,array_ejemplo2))
print(np.cross(array_ejemplo1,array_ejemplo2))
#haciendo uso de la funcion reshape para cambiar la disposicion de filas y columnas tiene que tener el numero adecuado de columnas y filas la otra opcion es la funcion flatten o ravel para aplanar el array
array2d_cambios= np.arange(20).reshape(2,10)
print("array aplanado",array2d_cambios.flatten())
"""
¿Qué es Matplotlib y en qué situaciones se usa en programación?

1. **Definición**:
   - Matplotlib es una biblioteca de Python para la creación de gráficos y visualizaciones de datos. 
     Es ampliamente utilizada para generar gráficos en 2D, como líneas, barras, dispersión, histogramas, 
     gráficos circulares y más.
   - La subbiblioteca más popular de Matplotlib es `pyplot`, que proporciona una interfaz similar a MATLAB, 
     simplificando la creación de gráficos.

2. **Características principales**:
   - Ofrece herramientas para personalizar todos los aspectos de un gráfico, como etiquetas, leyendas, 
     colores y estilos de líneas.
   - Permite exportar gráficos en varios formatos (PNG, PDF, SVG, etc.).
   - Integra bien con otras bibliotecas de análisis de datos, como NumPy, Pandas y SciPy.

3. **Situaciones en las que se utiliza**:
   - **Exploración de datos**: 
     Para visualizar y analizar patrones, tendencias o distribuciones en conjuntos de datos.
   - **Comunicación de resultados**: 
     Para crear gráficos que expliquen de manera visual los hallazgos en proyectos de ciencia de datos, 
     investigaciones o informes.
   - **Educación y enseñanza**: 
     Es útil en entornos educativos para explicar conceptos relacionados con gráficos o análisis de datos.
   - **Prototipos y desarrollo inicial**: 
     Se usa para generar gráficos rápidos mientras se trabaja en proyectos de análisis de datos.
   - **Complemento para aprendizaje automático**: 
     Ayuda a visualizar resultados de modelos, como métricas de precisión, curvas ROC o distribución de predicciones.

4. **Limitaciones**:
   - Aunque es poderoso, puede ser menos intuitivo para gráficos más avanzados, donde bibliotecas como 
     Seaborn o Plotly pueden ser más convenientes.
   - La personalización detallada puede requerir más esfuerzo en comparación con herramientas interactivas modernas.

En resumen, Matplotlib es una herramienta fundamental en programación para la visualización de datos, especialmente 
cuando se necesita un control detallado sobre la apariencia y el contenido de los gráficos.
"""






Tú dijiste:
quitame el en resumen humaniza el texto y doc string
ChatGPT Plus
ChatGPT
python
Copiar
Editar
"""
¿Qué es Matplotlib y en qué situaciones se usa en programación?

1. **Definición**:
   Matplotlib es una biblioteca de Python utilizada para crear gráficos y visualizaciones de datos. 
   Es una herramienta poderosa para generar gráficos en 2D, como gráficos de líneas, barras, dispersión, histogramas 
   o circulares. La subbiblioteca más conocida es `pyplot`, que simplifica el proceso de creación de gráficos 
   al proporcionar una interfaz similar a MATLAB.

2. **Características principales**:
   - Permite personalizar todos los elementos de un gráfico, como etiquetas, colores, estilos y leyendas.
   - Ofrece la posibilidad de exportar gráficos en distintos formatos, como PNG, PDF y SVG.
   - Funciona en conjunto con otras bibliotecas populares de Python, como NumPy, Pandas y SciPy.

3. **Situaciones en las que se utiliza**:
   - **Exploración de datos**: Ayuda a identificar patrones, tendencias o distribuciones en los datos.
   - **Presentación de resultados**: Es útil para comunicar hallazgos visualmente en informes, proyectos o investigaciones.
   - **Docencia**: Facilita la enseñanza de conceptos relacionados con gráficos y análisis de datos.
   - **Prototipado**: Se emplea para generar gráficos rápidos durante las etapas iniciales de análisis de datos.
   - **Modelos de aprendizaje automático**: Permite visualizar métricas, curvas ROC, distribuciones de predicciones, 
     entre otros aspectos de los modelos.

4. **Limitaciones**:
   Aunque Matplotlib es muy versátil, puede ser menos intuitivo para gráficos complejos o avanzados. En estos casos, 
   bibliotecas como Seaborn o Plotly pueden ser opciones más adecuadas. Además, personalizar ciertos detalles de los gráficos 
   puede requerir un esfuerzo considerable en comparación con otras herramientas interactivas modernas.
"""







[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]

 [[20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]]

 [[30 31]
  [32 33]
  [34 35]
  [36 37]
  [38 39]]]
[0 1 2 3 4 5 6 7 8 9]
[15  1  2  3  4  5  6  7  8  9]
[15  1  2  3  4  5  6  7]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
actuo sobre columnas [ 45 145]
actuo sobre columnas [10 12 14 16 18 20 22 24 26 28]
18
[-10  20 -10]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [1]:
!jupyter nbconvert --to pdf *.ipynb

[NbConvertApp] Converting notebook jupyter.ipynb to pdf
[NbConvertApp] Writing 41314 bytes to notebook.tex
[NbConvertApp] Building PDF
[NbConvertApp] Running xelatex 3 times: ['xelatex', 'notebook.tex', '-quiet']
[NbConvertApp] CRITICAL | x failed: xelatex notebook.tex -quiet
b''
Traceback (most recent call last):
  File "C:\Users\ia\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ia\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "g:\numpy\Scripts\jupyter-nbconvert.EXE\__main__.py", line 7, in <module>
    sys.exit(main())
  File "G:\numpy\lib\site-packages\jupyter_core\application.py", line 283, in launch_instance
    super().launch_instance(argv=argv, **kwargs)
  File "G:\numpy\lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "G:\numpy\lib\site-packages\nbconvert

In [26]:
print("version numpy",np.__version__)


version numpy 2.2.1
