In [1]:
import numpy as np

In [27]:
nombre_productos = np.array(["Smartphone","Tablet","Laptop","Auriculares","Teclado"])
print(nombre_productos)
cantidad_stock = np.array([["Smartphone",50],["Tablet",30],["Laptop",15],["Auriculares",40],["Teclado",60]])
print(cantidad_stock)
registro_ventas = np.array([[5, 3, 2, 6, 4],[7, 4, 1, 8, 5],[6, 2, 3, 5, 4]])
print(registro_ventas)
productos_no_vendidos = np.zeros((5,5))
print(productos_no_vendidos)
productos_en_promocion = np.ones((2,2))
productos_no_en_promocion = np.zeros((3,3))
print(productos_no_en_promocion)
print(productos_en_promocion)
precio_de_productos = np.arange(50,1000,50)
print(precio_de_productos)
cantidad_vendida = np.random.randint(low=1, high=10, size=5)
print(cantidad_vendida)
descuentos = np.empty((5,1))
print(descuentos)
cambio_ventas = np.linspace(0,1000,5)
print(cambio_ventas)















['Smartphone' 'Tablet' 'Laptop' 'Auriculares' 'Teclado']
[['Smartphone' '50']
 ['Tablet' '30']
 ['Laptop' '15']
 ['Auriculares' '40']
 ['Teclado' '60']]
[[5 3 2 6 4]
 [7 4 1 8 5]
 [6 2 3 5 4]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[ 50 100 150 200 250 300 350 400 450 500 550 600 650 700 750 800 850 900
 950]
[1 5 6 2 5]
[[2.31297541e-312]
 [2.41907520e-312]
 [2.37663529e-312]
 [2.35541533e-312]
 [2.14321575e-312]]
[   0.  250.  500.  750. 1000.]


In [17]:
#indexacion y seleccion de arrays con numpy ejercicio 3
array1d = np.arange(1,11)
print(array1d)
#array_tester = np.arange(1,9).reshape((3,3))
#print(array_tester)
#array_2d = array_base.reshape((3,3)) 
array2d = np.arange(9).reshape((3,3))
print(array2d)
print(array2d.ndim)
extraccion1d = int(array1d[0]),int(array1d[9])
print(array1d[0])
print(extraccion1d)
extraccion2d = array2d[0][0]
print(extraccion2d) 
extraccion2d_final = array2d[2][2]
print(extraccion2d_final)
ubicando_array2d = array2d[1][2]
print(ubicando_array2d)
print(array2d[0])
print(array2d[0][1])
print(array2d[1][1])
print(array2d[2][1])
#forma correcta preguntar 
print(array2d[:,1])


[ 1  2  3  4  5  6  7  8  9 10]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
2
1
(1, 10)
0
8
5
[0 1 2]
1
4
7
[1 4 7]


In [19]:
# pruebas
array2d = np.arange(9).reshape((3,3))
print(array2d)
print(array2d[0])
print(array2d[0][1])
print(array2d[1][1])
print(array2d[2][1])
print(array2d[0:2][1])
#forma correcta preguntar 
print(array2d[:,1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]
1
4
7
klk [3 4 5]
[1 4 7]


In [4]:
arraytester = np.random.randint(low=1, high=255,size=48)
print(arraytester)
rgb = arraytester.reshape(4,4,3)
print(rgb)
print("primer pixel",rgb[0,0, :])
print("ultimo pixel",rgb[-1,-1, :])
print("segunda fila tercera columna",rgb[0,1,2])
print("primera fila",rgb[0,:,:])
print ("canal azul",rgb[2,2 ,:])
print("recorte central",rgb[1:3, 1:3, :])

[115 130 117  69 170  17  88  10   1 199  63   3 175 186 186  20 145 184
 141 190   7  97 141  63 192 109 154  15 108  62 111 155 126 190 164 197
   8 191 198 183 219 243 102 123   2 201  62 175]
[[[115 130 117]
  [ 69 170  17]
  [ 88  10   1]
  [199  63   3]]

 [[175 186 186]
  [ 20 145 184]
  [141 190   7]
  [ 97 141  63]]

 [[192 109 154]
  [ 15 108  62]
  [111 155 126]
  [190 164 197]]

 [[  8 191 198]
  [183 219 243]
  [102 123   2]
  [201  62 175]]]


In [ ]:
Punto_1 = [2,3,5,7,11],[2,3,5,7,11]
Punto_2 = [1,4,6,8,10],[1,4,6,8,10]
array_1 = np.array(Punto_1)
array_2 = np.array(Punto_2)
print(np.linalg.norm(array_1-array_2))

In [8]:
calificaciones = np.array([
    [88, 78, 64, 92, 57, 70, 88, 68, 72, 60],
    [60, 73, 85, 89, 73, 52, 71, 51, 73, 93],
    [79, 87, 51, 70, 82, 61, 71, 93, 74, 98],
    [76, 91, 77, 65, 64, 96, 93, 52, 86, 56],
    [70, 58, 88, 67, 53, 74, 63, 99, 58, 75],
    [82, 79, 91, 88, 66, 78, 79, 63, 59, 89],
    [56, 66, 73, 77, 75, 80, 70, 64, 88, 60],
    [80, 62, 79, 85, 92, 72, 80, 69, 78, 66],
    [88, 90, 69, 77, 66, 72, 65, 73, 92, 81],
    [60, 80, 69, 94, 81, 88, 93, 60, 58, 79],
    [78, 72, 74, 81, 67, 93, 60, 72, 85, 92],
    [86, 90, 70, 64, 93, 58, 61, 95, 79, 84],
    [85, 77, 91, 85, 61, 63, 58, 68, 65, 90],
    [71, 79, 69, 58, 75, 78, 62, 82, 77, 59],
    [87, 76, 72, 68, 88, 65, 75, 90, 69, 79],
    [78, 71, 94, 67, 72, 88, 58, 79, 91, 67],
    [67, 64, 85, 81, 70, 84, 79, 73, 62, 77],
    [90, 61, 60, 91, 72, 89, 77, 75, 76, 83],
    [94, 83, 80, 59, 65, 75, 63, 92, 68, 60],
    [80, 81, 68, 95, 72, 93, 89, 59, 81, 85],
    [88, 63, 90, 77, 69, 72, 85, 78, 61, 93],
    [91, 65, 79, 92, 63, 74, 87, 70, 92, 85],
    [92, 80, 76, 72, 81, 87, 64, 74, 70, 67],
    [72, 83, 91, 58, 67, 88, 81, 76, 74, 92],
    [84, 91, 81, 77, 80, 63, 70, 79, 89, 65],
    [66, 65, 77, 58, 79, 61, 86, 72, 64, 74],
    [94, 74, 83, 89, 77, 68, 81, 92, 70, 68],
    [73, 72, 82, 80, 79, 64, 69, 60, 76, 79],
    [82, 79, 75, 89, 85, 81, 62, 64, 60, 92],
    [87, 88, 80, 74, 85, 90, 75, 68, 68, 71],
    [81, 79, 85, 76, 64, 85, 71, 77, 67, 93],
    [82, 89, 77, 72, 66, 84, 92, 60, 67, 65],
    [90, 63, 94, 67, 88, 93, 79, 64, 88, 80],
    [81, 90, 72, 76, 74, 93, 88, 84, 80, 65],
    [86, 75, 67, 81, 93, 79, 91, 64, 78, 74],
    [69, 85, 90, 91, 60, 76, 84, 78, 74, 64],
    [67, 91, 94, 78, 81, 73, 62, 67, 60, 92],
    [85, 79, 73, 60, 85, 90, 82, 75, 74, 68],
    [91, 83, 77, 92, 74, 68, 64, 92, 90, 92],
    [65, 93, 88, 82, 92, 67, 79, 68, 81, 93],
    [92, 79, 90, 92, 72, 80, 61, 75, 86, 90],
    [80, 67, 76, 84, 92, 90, 79, 93, 74, 88],
    [60, 79, 90, 93, 64, 61, 85, 76, 92, 72],
    [88, 67, 72, 64, 80, 90, 79, 75, 85, 81],
    [79, 92, 75, 72, 92, 81, 79, 70, 68, 68],
    [65, 60, 79, 89, 79, 82, 86, 64, 60, 81],
    [92, 81, 60, 79, 94, 78, 80, 91, 85, 68],
    [79, 64, 81, 72, 68, 75, 80, 94, 79, 61],
    [79, 94, 64, 89, 80, 85, 74, 82, 65, 91]
])
## axis 1 igual a columnas axix 0 igual a columas actua sobre las columas axix 1 actua sobre filas

normalizacionl2 = [ np.linalg.norm(calificacion) for calificacion in calificaciones]
print("la normalizacion l2 ", normalizacionl2)
for x in range(len(normalizacionl2)):
    print("la normalizacion por asignatura es :",normalizacionl2[x])
for x in range(10):
    print("calificaciones por asignatura",np.linalg.norm(calificaciones[:,x]))
for x in range(len(calificaciones[0])):
    print("calificaciones por asignatura con  otro metodo",np.linalg.norm(calificaciones[:,x]))
    print("asignatura",x)
print("las calificaciones utilizando axis",np.linalg.norm(calificaciones, axis=0, keepdims=True ))
print("la sumas de todas las calificaciones por  asignatura",np.sum(calificaciones,axis=0))
print("la suma de todas las notas",np.sum(calificaciones,axis=1))


    




la normalizacion l2  [np.float64(235.98516902551313), np.float64(231.7930111112067), np.float64(246.02032436365903), np.float64(243.73756378531397), np.float64(227.02643017939565), np.float64(247.06679258856298), np.float64(226.0862667213557), np.float64(242.81474419812318), np.float64(246.2782978664584), np.float64(244.45040396775784), np.float64(246.81166909204273), np.float64(250.0959815750745), np.float64(238.03991261971174), np.float64(226.03981950090122), np.float64(244.64055264816582), np.float64(244.44426767670376), np.float64(235.94490882407274), np.float64(247.0344105585293), np.float64(236.8818270783979), np.float64(256.18547968220213), np.float64(247.7216179504728), np.float64(254.58593833909995), np.float64(242.72412323458911), np.float64(249.4554068365727), np.float64(247.9576576756604), np.float64(223.5799633240868), np.float64(253.42454498331452), np.float64(233.13515393436487), np.float64(245.56261930513773), np.float64(249.85595850409493), np.float64(247.4510052515447

In [14]:
v1 = [3, 4, 0]
v2 = [4, 3, 1]
print(np.cross(v1,v2))
extra_v1 = [3, 2, 0]
extra_v2 = [4, 1, 12]
print(np.cross(extra_v1,extra_v2))
extra_v1_2d = [3, 2]
extra_v2_2d = [4, 1]
print(np.cross(extra_v1_2d,extra_v2_2d))

[ 4 -3 -7]
[ 24 -36  -5]
-5


C:\Users\Manu\AppData\Local\Temp\ipykernel_19276\374326904.py:9: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  print(np.cross(extra_v1_2d,extra_v2_2d))


In [19]:
tiempo_atleta = np.array([11, 22, 50, 110, 250])
print(tiempo_atleta)
importancia_pruebas = np.array([0.4, 0.3, 0.2, 0.1, 0.05])
print(np.dot(tiempo_atleta,importancia_pruebas))

[ 11  22  50 110 250]
44.5


In [27]:
jugadores = np.array([
    [10,7,300,25,40],
    [15,10,250,30,50],
    [5,12,280,20,35],
    [8,6,310,15,38],
    [12,9,270,28,45]
])
print(jugadores)
jugadores_normalizados = jugadores / np.linalg.norm(jugadores,axis=1)
print(jugadores_normalizados)

[[ 10   7 300  25  40]
 [ 15  10 250  30  50]
 [  5  12 280  20  35]
 [  8   6 310  15  38]
 [ 12   9 270  28  45]]
[[0.03290221 0.02720114 1.05937646 0.079913   0.14515829]
 [0.04935332 0.03885877 0.88281371 0.0958956  0.18144787]
 [0.01645111 0.04663052 0.98875136 0.0639304  0.12701351]
 [0.02632177 0.02331526 1.094689   0.0479478  0.13790038]
 [0.03948266 0.03497289 0.95343881 0.08950256 0.16330308]]


In [1]:
!jupyter nbconvert --to pdf *.ipynb

[NbConvertApp] Converting notebook jupyter.ipynb to pdf
[NbConvertApp] Writing 41314 bytes to notebook.tex
[NbConvertApp] Building PDF
[NbConvertApp] Running xelatex 3 times: ['xelatex', 'notebook.tex', '-quiet']
[NbConvertApp] CRITICAL | x failed: xelatex notebook.tex -quiet
b''
Traceback (most recent call last):
  File "C:\Users\ia\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ia\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "g:\numpy\Scripts\jupyter-nbconvert.EXE\__main__.py", line 7, in <module>
    sys.exit(main())
  File "G:\numpy\lib\site-packages\jupyter_core\application.py", line 283, in launch_instance
    super().launch_instance(argv=argv, **kwargs)
  File "G:\numpy\lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "G:\numpy\lib\site-packages\nbconvert

In [26]:
print("version numpy",np.__version__)


version numpy 2.2.1
