In [2]:
import numpy as np 

In [42]:
array = np.arange(25)
print(array.reshape(5, 5))
print(len(array))
print(array[:24].reshape(1,4,6))
#print(array.reshape(2, 4))
print(array.ravel())
transposed = array.T
print(transposed)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
25
[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [45]:



array_2d = np.random.randint(low=1, high=8,size=4).reshape(2,2)
array2d1= np.random.randint(low=3, high=6,size=4).reshape(2,2)
print(array_2d)
print(array2d1)
suma=array_2d+array2d1
resta=array_2d-array2d1
multiplicacion=array_2d*array2d1
division=array_2d/array2d1
print("esta es la suma",suma)
print("esta es la resta",resta)
print("esta es la multiplicacion",multiplicacion)
print("esta es la division",division)
print("esta es la suma con el scalar",array_2d+6)
print("esta es la resta con scalar",array_2d-6)
print("esta es la multiplicacion con scalar",array_2d*6)
print("esta es la division con scalar",array_2d/6)
vector= np.random.randint(low=1, high=8,size=25)
print(vector)
print(np.cumsum(vector))
vector_flotantes = np.random.random(size=25)
print(np.cumsum(vector_flotantes))



[[7 4]
 [1 4]]
[[5 3]
 [4 3]]
esta es la suma [[12  7]
 [ 5  7]]
esta es la resta [[ 2  1]
 [-3  1]]
esta es la multiplicacion [[35 12]
 [ 4 12]]
esta es la division [[1.4        1.33333333]
 [0.25       1.33333333]]
esta es la suma con el scalar [[13 10]
 [ 7 10]]
esta es la resta con scalar [[ 1 -2]
 [-5 -2]]
esta es la multiplicacion con scalar [[42 24]
 [ 6 24]]
esta es la division con scalar [[1.16666667 0.66666667]
 [0.16666667 0.66666667]]
[5 1 1 5 6 5 4 4 6 2 2 5 2 5 2 1 1 4 4 7 3 7 2 6 6]
[ 5  6  7 12 18 23 27 31 37 39 41 46 48 53 55 56 57 61 65 72 75 82 84 90
 96]
[ 0.08520197  0.41884132  0.94129872  1.50242555  2.24513487  2.44848448
  3.33897301  3.3992439   3.8231057   4.54957274  5.23193819  5.65223321
  6.1893026   6.42591894  6.99339258  7.11188328  7.42059983  7.71981543
  8.10740988  8.25138763  9.15075116  9.5288887  10.46662121 10.57652747
 10.92143761]


In [6]:
vector_a = np.random.randint(low=1, high=255,size=3)
print("mostrar vector",vector_a)
vector_b = np.random.randint(low=1,high=255,size=3)
print("mostrar vector 2",vector_b)
producto_punto = np.dot(vector_a, vector_b)

print("Producto punto:", producto_punto)

vector_a_cruzado = np.random.randint(low=1,high=255,size=3)
print("mostrar vector",vector_a_cruzado)
vector_b_cruzado = np.random.randint(low=1,high=255,size=3)
print("mostrar vector",vector_b_cruzado)


# Calculamos el producto cruzado entre los dos vectores
producto_cruzado = np.cross(vector_a, vector_b)

print("Producto cruzado:", producto_cruzado)
array_euclidiano = np.arange(5,20,5)
print(array_euclidiano)
array_euclidiano_2 = np.arange(100,400,100)
print(array_euclidiano_2)
distancia = np.linalg.norm(array_euclidiano-array_euclidiano_2)
print("formula automatica",distancia)
def distancia_euclidiana(v1, v2):
    return np.sqrt(np.sum((v1 - v2) ** 2)) 
distancia_euclidiana_2 = distancia_euclidiana(array_euclidiano,array_euclidiano_2)
print("formula a mano",distancia_euclidiana_2)
#calcular la distancia a un punto origen
distancia_origen=np.sqrt(np.sum(array_euclidiano**2))
print("formula",distancia_origen)
distancia_origen_l2 = np.linalg.norm(array_euclidiano)
print("formula ya hecha",distancia_origen_l2)
distancia_origen_2 = np.sqrt(np.sum(array_euclidiano_2**2))
print("con formula segundo array ",distancia_origen_2)
distancia_origen_formula = np.linalg.norm(array_euclidiano_2)
print("con formula ya hecha segundo array",distancia_origen_formula)



mostrar vector [216 131 214]
mostrar vector 2 [137 170  34]
Producto punto: 59138
mostrar vector [196 206 152]
mostrar vector [ 37  72 246]
Producto cruzado: [-31926  21974  18773]
[ 5 10 15]
[100 200 300]
formula automatica 355.4574517435244
formula a mano 355.4574517435244
formula 18.708286933869708
formula ya hecha 18.708286933869708
